### ISSUE TITLE
How can you make sure the rider have enough time when he receive the information

### ISSUE THREAD

**Issue by JiananKan** [tamercos/PiCycleSEAT#5]
How many threads are needed and/or how can the load be distributed to
allow a responsive application?
team 6

**Comment by tamercos** [comment]
Due to the relatively low sample rate that is required, we only need one thread to run the program with no observable latency issues. We still need to update the wiki/readme regarding detailed information, but currently each sensor is sampling at 50Hz with the UI called upon every 40ms. These are subject to change, but these numbers accommodate for sufficiently low latency with no load issues and plenty information being passed to the rider.

Multi-threading may still be implemented if it is deemed required in the future.

Thank you for your comment!
