### ISSUE TITLE
Thread

### ISSUE THREAD

**Issue by Cao-Jinyu** [tamercos/PiCycleSEAT#7]
How many threads do you use in your project? I can only find one thread. Could you use muti-thread to make it more efficient?

**Comment by tamercos** [comment]
As of now the program runs perfectly well with just one thread due to the sufficiently low sample rate that's required, both from the control code and the UI. Each sensor is currently set to 50 Hz sample rate with the UI called upon every 40ms. These are subject to change with further developments but as of now there are no hickups regarding the efficiency of the code.

Multi-threading may still be implemented if its deemed required in the future, but for now I'm going to close this issue.

Thank you for your comment!
